{ config, pkgs, lib, ... }:
{
    # https://discourse.nixos.org/t/flake-to-create-a-simple-sd-image-for-rpi4-cross/35185/24

    # Define Secrets Locations
    #age.secrets."wifi-pswd".file = ../secrets/wifi-pswd.age;
    #age.secrets."nixpi-andrew-pswd".file = ../secrets/nixpi-andrew-pswd.age;

    # TODO: get hardware scan
    # actually, do I even need to HW scan??
    imports = [
        # Include the results of the hardware scan.
        ./hardware-configuration.nix
    ];



    # Enable automatic garbage collection
    nix.gc.automatic = true;

    networking.hostName = "nixPi"; # Define your hostname.

    # Testing out GNOME desktop
    #services.xserver.enable = true;
    #services.xserver.displayManager.gdm.enable = true;
    #services.xserver.desktopManager.gnome.enable = true;

    #networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
    #passphrase = builtins.readFile config.age.secrets."wifi-pswd".path;
    #networking.wireless = {
     #   enable = true;
        # networks = {
        #     ClickHereForViruses = {
        #         psk = builtins.readFile config.age.secrets."wifi-pswd".path;
        #     };
        # };
    #};

    # networking.networkmanager.ensureProfiles = {
    #     environmentFiles = [
    #         config.age.secrets."wifi-pswd".path
    #     ];

    #     profiles = {
    #         ClickHereForViruses = {
    #             connection = {
    #                 id = "ClickHereForViruses";
    #                 type = "wifi";
    #             };
    #             wifi = {
    #                 mode = "infrastructure";
    #                 ssid = "ClickHereForViruses";
    #             };
    #             wifi-security = {
    #                 key-mgmt = "wpa-psk";
    #                 psk = "$PSK";
    #             };
    #         };
    #     };
    # };

    # Enable networking
    networking.networkmanager.enable = true;

    # Set your time zone.
    time.timeZone = "America/New_York";

    # Allow unfree packages
    nixpkgs.config.allowUnfree = true;

    # Enable flakes
    nix.settings.experimental-features = [
        "nix-command"
        "flakes"
    ];

    # TODO: configure user password
    users.users.andrew = {
        name = "andrew";
        isNormalUser = true;
        description = "andrew";
        initialPassword = "raspberrypi";
        #passwordFile = config.age.secrets."nixpi-andrew-pswd".path;
        extraGroups = [
            "networkmanager"
            "wheel"
        ];
    };

    # List packages installed in system profile. To search, run:
    # $ nix search wget
    environment.systemPackages = with pkgs; [
        vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
        wget
        fastfetch
        fail2ban
        git
        manix # for looking up nix documentation
        htop
        nixfmt-rfc-style # autoformatter
        jupyter-all # jupyter packaged with ipython, etc.
        tmux
        cowsay
    ];
    
    # Enable the OpenSSH daemon.
    services.openssh = {
        enable = true;
        settings.PasswordAuthentication = false;
    };
    users.users."andrew".openssh.authorizedKeys.keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFTSJ+CahcqGec/tsOcZDxsAyFQ1h8TxCgVxq1bSePr jonathanstewart"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOxu3rKajcleNImRxfg1M9u0xHm3fh5dZ5XH/V6UQhK4 Generated By Termius"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKeyCw1VxK87xr+cYZdjqW/MIPTjxzOg7q7isrn3bdC4"

        # content of authorized_keys file
        # note: ssh-copy-id will add user@your-machine after the public key
        # but we can remove the "@your-machine" part
    ];

    # TODO: finish tailscale config by establishing secrets management
    services.tailscale = {
        enable = true;
        useRoutingFeatures = "both";
        extraUpFlags = [ "--advertise-exit-node" ];
    };

    # This value determines the NixOS release from which the default
    # settings for stateful data, like file locations and database versions
    # on your system were taken. It‘s perfectly fine and recommended to leave
    # this value at the release version of the first install of this system.
    # Before changing this value read the documentation for this option
    # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
    system.stateVersion = "24.11"; # Did you read the comment?
}