# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tekkit-classic" = {
    image = "localhost/tekkit-classic:local";
    environment = {
      "ALLOW_FLIGHT" = "true";
      "DIFFICULTY" = "1";
      "GAMEMODE" = "0";
      "JAVA_MEMORY" = "2G";
      "JAVA_OPTS" = "-XX:+UseG1GC -XX:+UseStringDeduplication";
      "MAX_PLAYERS" = "20";
      "MOTD" = "Tekkit Classic Server";
      "ONLINE_MODE" = "true";
      "PVP" = "true";
      "SERVER_PORT" = "25565";
      "VIEW_DISTANCE" = "10";
    };
    volumes = [
      "tekkit_tekkit-server-data:/server:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tekkit"
      "--network=tekkit_default"
    ];
  };
  systemd.services."podman-tekkit-classic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-build-tekkit-classic.service"
      "podman-network-tekkit_default.service"
      "podman-volume-tekkit_tekkit-server-data.service"
    ];
    requires = [
      "podman-build-tekkit-classic.service"
      "podman-network-tekkit_default.service"
      "podman-volume-tekkit_tekkit-server-data.service"
    ];
    partOf = [
      "podman-compose-tekkit-root.target"
    ];
    wantedBy = [
      "podman-compose-tekkit-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-tekkit_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tekkit_default";
    };
    script = ''
      podman network inspect tekkit_default || podman network create tekkit_default
    '';
    partOf = [ "podman-compose-tekkit-root.target" ];
    wantedBy = [ "podman-compose-tekkit-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-tekkit_tekkit-server-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect tekkit_tekkit-server-data || podman volume create tekkit_tekkit-server-data
    '';
    partOf = [ "podman-compose-tekkit-root.target" ];
    wantedBy = [ "podman-compose-tekkit-root.target" ];
  };

  # Builds
  systemd.services."podman-build-tekkit-classic" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      TimeoutSec = 300;
    };
    script = ''
      podman build -t tekkit-classic:local https://github.com/andrew2165/Tekkit-Classic-Docker.git
    '';
    partOf = [ "podman-compose-tekkit-root.target" ];
    wantedBy = [ "podman-compose-tekkit-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tekkit-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
