services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ~/mealie/data:/app/data/
    env_file: "/etc/mealie/mealie/.env"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - ~/mealie/mealie-pgdata:/var/lib/postgresql/data
    env_file: "/etc/mealie/postgres/.env"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
  mealie-pgdata: