# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."paper-geyser" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "ENABLE_RCON" = "true";
      "EULA" = "TRUE";
      "MEMORY" = "4G";
      "PLUGINS" = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
  https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  ";
      "RCON_PASSWORD" = "change-me";
      "TYPE" = "PAPER";
    };
    volumes = [
      "mc-paper-geyser_mc-data:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
      "19132:19132/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=mc-paper-geyser_default"
    ];
  };
  systemd.services."podman-paper-geyser" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-mc-paper-geyser_default.service"
      "podman-volume-mc-paper-geyser_mc-data.service"
    ];
    requires = [
      "podman-network-mc-paper-geyser_default.service"
      "podman-volume-mc-paper-geyser_mc-data.service"
    ];
    partOf = [
      "podman-compose-mc-paper-geyser-root.target"
    ];
    wantedBy = [
      "podman-compose-mc-paper-geyser-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-mc-paper-geyser_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f mc-paper-geyser_default";
    };
    script = ''
      podman network inspect mc-paper-geyser_default || podman network create mc-paper-geyser_default
    '';
    partOf = [ "podman-compose-mc-paper-geyser-root.target" ];
    wantedBy = [ "podman-compose-mc-paper-geyser-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-mc-paper-geyser_mc-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect mc-paper-geyser_mc-data || podman volume create mc-paper-geyser_mc-data --driver=local
    '';
    partOf = [ "podman-compose-mc-paper-geyser-root.target" ];
    wantedBy = [ "podman-compose-mc-paper-geyser-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mc-paper-geyser-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
